apiVersion: v1
kind: Secret
metadata:
  name: argo-oci
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: argo-oci
  type: helm
  url: oci://ghcr.io/argoproj/argo-helm
  enableOCI: "true"
  insecure: "true"
